version: '3.0'

services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
      - .:/code
    networks:
      - web
  server:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    volumes:
      - .:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - web

networks:
  web: